image:
    file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 9000-9800
    onOpen: ignore
  - port: 1000-5999
    onOpen: ignore
tasks:
  - command: cd crash-course-ruby/local && gem install bundler && bundle install
    name: Install Local Ruby Gems
  - command: cd crash-course-ruby/sauce && gem install bundler && bundle install
    name: Install Sauce Ruby Gems
  - command: cd crash-course-python/local && pip install -r requirements.txt
    name: Install Local Python Dependencies
  - command: cd crash-course-python/sauce && pip install -r requirements.txt
    name: Install Sauce Python Dependencies